# Generated by Django 3.2.8 on 2021-10-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=60, null=True)),
                ('level', models.CharField(max_length=100)),
                ('estimated_duration', models.CharField(max_length=10)),
            ],
        ),
    ]
