# Generated by Django 3.2.8 on 2021-10-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_developermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='developermodel',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='developermodel',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='developermodel',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
