# Generated by Django 3.2.8 on 2021-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211014_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developermodel',
            name='estimated_duration',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='developermodel',
            name='level',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developermodel',
            name='task',
            field=models.CharField(blank=True, default='None', max_length=60, null=True),
        ),
    ]
