# Generated by Django 3.2.8 on 2021-10-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211014_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='developermodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
