# Generated by Django 3.2.8 on 2021-10-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_developermodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('level', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('duration', models.CharField(blank=True, default='None', max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='name',
            field=models.CharField(blank=True, choices=[('Provider 1', 'Provider 1'), ('Provider 2', 'Provider 2')], max_length=60, null=True),
        ),
    ]
