# Generated by Django 3.2.8 on 2021-10-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211015_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developermodel',
            old_name='estimated_duration',
            new_name='duration',
        ),
    ]
